# Generated by Django 4.2.2 on 2023-06-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='id_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
