# Generated by Django 4.2.2 on 2023-06-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_type_of_animal_pet_type_of_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_of_animal',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='вид'),
        ),
    ]
