# Generated by Django 4.2.2 on 2023-06-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_type_of_animal_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='cat',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='type_of_animal',
            name='slug',
        ),
    ]
