# Generated by Django 4.2.2 on 2023-06-20 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_cat_pet_category_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('additional_information', models.TextField(blank=True, verbose_name='Текст статьи')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.category', verbose_name='Категории')),
                ('type_of_animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.type_of_animal', verbose_name='вид')),
            ],
            options={
                'verbose_name': 'pet',
                'verbose_name_plural': 'pet',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='pet',
        ),
    ]
