# Generated by Django 4.2.2 on 2023-06-20 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_posts_delete_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='staus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='вид')),
            ],
            options={
                'verbose_name': 'staus',
                'verbose_name_plural': 'staus',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='posts',
            name='staus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.staus', verbose_name='staus'),
            preserve_default=False,
        ),
    ]
