# Generated by Django 4.2.2 on 2023-06-20 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_staus_posts_staus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staus',
            new_name='status',
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['id'], 'verbose_name': 'status', 'verbose_name_plural': 'status'},
        ),
        migrations.RemoveField(
            model_name='posts',
            name='staus',
        ),
        migrations.AddField(
            model_name='posts',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.status', verbose_name='status'),
            preserve_default=False,
        ),
    ]
