# Generated by Django 4.2.2 on 2023-06-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_staus_status_alter_status_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='is_published',
        ),
    ]
