# Generated by Django 4.2.2 on 2023-06-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_posts_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='вид')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'role',
                'ordering': ['id'],
            },
        ),
    ]
